In [45]:
import numpy as np
import pandas as pd
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix
from sklearn.externals import joblib

In [35]:
X = pd.read_csv("F:/Final Project/Final Dataset/final-values.csv")

In [36]:
X.head()

Country  Employement  Education  Major  DevType  Target
0       18            1          1      9        6       6
1       31            0          1      3        2       2
2       32            0          0      6        2       2
3       32            0          1      6        6       6
4       25            0          4      6        1       1

In [37]:
X_train, X_test = train_test_split(X, test_size = 0.25, random_state = 0)

In [38]:
X_Train = X_train.iloc[:, [0,1,2,3,4]].values
Y_Train = X_train.iloc[:, 5].values

#print(X_Train)
#print(Y_Train)

In [39]:
X_Test = X_test.iloc[:, [0,1,2,3,4]].values
Y_Test = X_test.iloc[:, 5].values

#print(X_Test)
#print(Y_Test)

In [40]:
sc = StandardScaler()
X_Train = sc.fit_transform(X_Train)

In [41]:
classifier = GaussianNB()
classifier.fit(X_Train,Y_Train)

GaussianNB(priors=None)

In [42]:
X_Test = sc.fit_transform(X_Test)

C:\Users\Sushil\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [43]:
Y_pred = classifier.predict(X_Test)

In [44]:
cm = confusion_matrix(Y_Test, Y_pred)
print(cm)

[[9 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 6 0 0]
 [0 0 0 0 0 3 0]]


In [48]:
naivebayes_model = open("F:/Final Project/Flask/models/NBClassifier.pkl","rb")
clf = joblib.load(naivebayes_model)

In [49]:
myprediction = clf.predict(X_Test)

In [51]:
ccm = confusion_matrix(Y_Test, myprediction)
print(ccm)

[[9 0 0 0 0 0 0]
 [0 1 0 0 0 0 0]
 [0 0 3 0 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 0 3 0 0]
 [0 0 0 0 0 6 0]
 [0 0 0 0 0 0 3]]
