In [2]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import GaussianNB
from sklearn import metrics
from sklearn.preprocessing import StandardScaler

In [3]:
X = pd.read_csv("Final Dataset/final-values.csv")
X.head()

Country  Employement  Education  Major  DevType  Target
0       18            1          1      9        6       6
1       31            0          1      3        2       2
2       32            0          0      6        2       2
3       32            0          1      6        6       6
4       25            0          4      6        1       1

In [4]:

#Training Set

X_Train = X.iloc[:99, [0,1,2,3,4]].values
Y_Train = X.iloc[:99, 5].values

#print(X_Train)
#print(Y_Train)

In [5]:
# Feature Scaling

sc = StandardScaler()
X_Train = sc.fit_transform(X_Train)
print(X_Train)

[[-0.20178767  3.37268439 -0.6918711   2.1495802   1.11291803]
 [ 1.07752627 -0.29649973 -0.6918711  -1.56219491 -0.38611442]
 [ 1.17593504 -0.29649973 -1.58141965  0.29369264 -0.38611442]
 [ 1.17593504 -0.29649973 -0.6918711   0.29369264  1.11291803]
 [ 0.48707368 -0.29649973  1.97677456  0.29369264 -0.76087253]
 [ 1.07752627 -0.29649973 -0.6918711   0.29369264 -1.13563064]
 [ 1.17593504 -0.29649973  1.97677456  0.29369264 -1.13563064]
 [ 0.09343863 -0.29649973 -0.6918711   0.29369264 -0.01135631]
 [ 1.17593504 -0.29649973  1.97677456  0.91232183  1.11291803]
 [-0.69383149 -0.29649973 -0.6918711   0.29369264 -0.01135631]
 [ 0.58548245 -0.29649973  0.19767746  1.53095102 -1.13563064]
 [-0.69383149 -0.29649973 -0.6918711  -0.32493654  0.73815992]
 [-1.18587532 -0.29649973  1.97677456  0.29369264 -1.13563064]
 [-0.69383149 -0.29649973 -0.6918711  -0.32493654  1.11291803]
 [-0.00497014 -0.29649973  1.08722601 -1.56219491  0.73815992]
 [-0.3986052  -0.29649973  0.19767746  0.91232183  1.11

C:\Users\Sushil\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)


In [9]:
#Classifier

classifier = GaussianNB()
classifier.fit(X_Train,Y_Train)

GaussianNB(priors=None)

In [10]:
#Test Set
X_Test = X.iloc[102:,[0,1,2,3,4]].values
#print(X_Test)

Y_Test = X.iloc[100:,5].values
#print(Y_Test)

X_Test = sc.fit_transform(X_Test)
print(X_Test)

Y_pred = classifier.predict(X_Test)
print(Y_pred)
print(Y_Test)

[[0. 0. 0. 0. 0.]]
[3]
[0 0 6]


C:\Users\Sushil\Anaconda3\lib\site-packages\sklearn\utils\validation.py:475: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, DataConversionWarning)
